export const OPEN_DELETE_ITEM_DIALOG = "OPEN_DELETE_ITEM_DIALOG";
export const CLOSE_DELETE_ITEM_DIALOG = "CLOSE_DELETE_ITEM_DIALOG";

export const OPEN_DELETE_COLUMN_DIALOG = "OPEN_DELETE_COLUMN_DIALOG";
export const CLOSE_DELETE_COLUMN_DIALOG = "CLOSE_DELETE_COLUMN_DIALOG";

export const OPEN_EDIT_ITEM_DIALOG = "OPEN_EDIT_ITEM_DIALOG";
export const CLOSE_EDIT_ITEM_DIALOG = "CLOSE_EDIT_ITEM_DIALOG";
