module.exports = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CREATE_CARD: "create card",
  CREATE_COLUMN: "create column",
  DELETE_COLUMN: "delete column",
  UPDATE_BOARD: "update board",
  VOTE_CARD: "vote card",
  EDIT_CARD: "edit card",
  SORT_COLUMN: "sort column",
  DELETE_CARD: "delete card",
  JOIN_BOARD: "join board",
  UNBLUR_CARDS: "unblur cards",
  EDIT_COLUMN: "edit column",
  JOIN_ERROR: "join error",
  SET_MAX_VOTES: "set max votes",
  RESET_VOTES: "reset votes",
  FOCUS_CARD: "focus card",
  REMOVE_FOCUS_CARD: "remove focus card",
  SHOW_CONTINUE_DISCUSSION: "show continue discussion"
};
