version: "3.9"
services:
  frontend:
    image: retroapp/retro-frontend
    ports:
      - "80:80"
  backend:
    image: retroapp/retro-backend
    ports:
      - "3001:3001"
  signaling:
    container_name: retro-signaling
    image: peerjs/peerjs-server
    ports:
      - "3002:9000"
