export const SET_FOCUSED_CARD = "SET_FOCUSED_CARD";
export const REMOVE_FOCUSED_CARD = "REMOVE_FOCUSED_CARD";
export const SET_CONTINUE_DISCUSSION = "SET CONTINUE DISCUSSION";
export const CONTINUE_DISCUSSION_VOTE_YES = "CONTINUE DISCUSSION VOTE YES";
export const CONTINUE_DISCUSSION_VOTE_NO = "CONTINUE DISCUSSION VOTE NO";
export const CONTINUE_DISCUSSION_VOTE_ABSTAIN =
  "CONTINUE DISCUSSION VOTE ABSTAIN";
