name: Retro CD

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: "Docker tag"
        required: true
        default: "latest"
      commitRef:
        description: "Commit hash or branch"
        required: true
        default: "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.commitRef }}

      - name: Publish Frontend Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          default_branch: master
          name: retroapp/retro-frontend
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ github.event.inputs.dockerTag }}, latest"
          dockerfile: ./packages/frontend/Dockerfile

      - name: Publish Backend Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          default_branch: master
          name: retroapp/retro-backend
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ github.event.inputs.dockerTag }}, latest"
          dockerfile: ./packages/backend/Dockerfile
