name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  runs-on: "ubuntu-latest"
  env:
    working-directory: ./
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: "19"
        cache: npm

    - name: Install Dependencies
      run: npm ci

    - name: Lint files
      run: npm run format:check
      working-directory: ${{env.working-directory}}

    - name: Run Prettier
      run: npm run lint
      working-directory: ${{env.working-directory}}
